LPPsystem pulsePropagation

	SPsystems
		SPsystem senderCell from senderCell.sps
		SPsystem pulsingCell from pulsingCell.sps
		SPsystem boundaryCell from boundaryCell.sps
	endSPsystems

	lattice rectangular from lattice.lat

	spatialDistribution

		positions for boundaryCell
			parameters
				parameter i = 0:1:30
				parameter j = 0:5:5
			endParameters
			coordinates
				x = i
				y = j
			endCoordinates
		endPositions
			
		positions for boundaryCell
			parameters
				parameter i = 0:30:30
				parameter j = 1:1:4
			endParameters
			coordinates
				x = i
				y = j
			endCoordinates
		endPositions

		
		positions for senderCell
			parameters
				parameter i = 1:1:5
				parameter j = 1:1:4
			endParameters

			coordinates
				x=i
				y=j
			endCoordinates
		endPositions

		positions for pulsingCell
			parameters
				parameter i=6:1:29
				parameter j=1:1:4
			endParameters
		
			coordinates
				x=i
				y=j
			endCoordinates
		endPositions

	endSpatialDistribution

endLPPsystem
