# Fake import list
if False:
    import enthought
    import enthought.pyface.api
    import enthought.pyface.action.api
    import enthought.pyface.workbench
    import enthought.etsconfig
    import enthought.pyface.ui.wx
    import enthought.pyface
    import enthought.pyface.ui
    import enthought.pyface.ui.wx
    import enthought.pyface.ui.wx.about_dialog
    import enthought.pyface.ui.wx.application_window
    import enthought.pyface.ui.wx.confirmation_dialog
    import enthought.pyface.ui.wx.dialog
    import enthought.pyface.ui.wx.directory_dialog
    import enthought.pyface.ui.wx.file_dialog
    import enthought.pyface.ui.wx.gui
    import enthought.pyface.ui.wx.heading_text
    import enthought.pyface.ui.wx.image_cache
    import enthought.pyface.ui.wx.image_resource
    import enthought.pyface.ui.wx.init
    import enthought.pyface.ui.wx.message_dialog
    import enthought.pyface.ui.wx.progress_dialog
    import enthought.pyface.ui.wx.python_editor
    import enthought.pyface.ui.wx.python_shell
    import enthought.pyface.ui.wx.resource_manager
    import enthought.pyface.ui.wx.splash_screen
    import enthought.pyface.ui.wx.split_widget
    import enthought.pyface.ui.wx.system_metrics
    import enthought.pyface.ui.wx.widget
    import enthought.pyface.ui.wx.window
    import enthought.pyface.ui.wx.action
    import enthought.pyface.ui.wx.action.action_item
    import enthought.pyface.ui.wx.action.menu_bar_manager
    import enthought.pyface.ui.wx.action.menu_manager
    import enthought.pyface.ui.wx.action.status_bar_manager
    import enthought.pyface.ui.wx.action.tool_bar_manager
    import enthought.pyface.ui.wx.action.tool_palette
    import enthought.pyface.ui.wx.action.tool_palette_manager
    import enthought.pyface.ui.wx.timer
    import enthought.pyface.ui.wx.timer.do_later
    import enthought.pyface.ui.wx.timer.timer
    import enthought.pyface.ui.wx.wizard
    import enthought.pyface.ui.wx.wizard.wizard
    import enthought.pyface.ui.wx.wizard.wizard_page
    import enthought.pyface.ui.wx.workbench
    import enthought.pyface.ui.wx.workbench.editor
    import enthought.pyface.ui.wx.workbench.editor_set_structure_handler
    import enthought.pyface.ui.wx.workbench.view
    import enthought.pyface.ui.wx.workbench.view_set_structure_handler
    import enthought.pyface.ui.wx.workbench.workbench_dock_window
    import enthought.pyface.ui.wx.workbench.workbench_window_layout
    import enthought.traits
    import enthought.traits.ui
    import enthought.traits.ui.wx
    import enthought.traits.ui.wx.animated_gif_editor
    import enthought.traits.ui.wx.animated_gif_editor_26
    import enthought.traits.ui.wx.animated_gif_editor_28
    import enthought.traits.ui.wx.array_editor
    import enthought.traits.ui.wx.basic_editor_factory
    import enthought.traits.ui.wx.boolean_editor
    import enthought.traits.ui.wx.button_editor
    import enthought.traits.ui.wx.check_list_editor
    import enthought.traits.ui.wx.code_editor
    import enthought.traits.ui.wx.color_column
    import enthought.traits.ui.wx.color_editor
    import enthought.traits.ui.wx.color_trait
    import enthought.traits.ui.wx.compound_editor
    import enthought.traits.ui.wx.constants
    import enthought.traits.ui.wx.custom_editor
    import enthought.traits.ui.wx.directory_editor
    import enthought.traits.ui.wx.dnd_editor
    import enthought.traits.ui.wx.drop_editor
    import enthought.traits.ui.wx.editor
    import enthought.traits.ui.wx.editor_factory
    import enthought.traits.ui.wx.enum_editor
    import enthought.traits.ui.wx.file_editor
    import enthought.traits.ui.wx.font_editor
    import enthought.traits.ui.wx.font_trait
    import enthought.traits.ui.wx.helper
    import enthought.traits.ui.wx.history_control
    import enthought.traits.ui.wx.history_editor
    import enthought.traits.ui.wx.html_editor
    import enthought.traits.ui.wx.image_control
    import enthought.traits.ui.wx.image_editor
    import enthought.traits.ui.wx.image_enum_editor
    import enthought.traits.ui.wx.image_panel
    import enthought.traits.ui.wx.image_slice
    import enthought.traits.ui.wx.image_text
    import enthought.traits.ui.wx.instance_editor
    import enthought.traits.ui.wx.key_binding_editor
    import enthought.traits.ui.wx.key_event_to_name
    import enthought.traits.ui.wx.list_editor
    import enthought.traits.ui.wx.list_str_editor
    import enthought.traits.ui.wx.menu
    import enthought.traits.ui.wx.null_editor
    import enthought.traits.ui.wx.popup_editor
    import enthought.traits.ui.wx.range_editor
    import enthought.traits.ui.wx.rgb_color_editor
    import enthought.traits.ui.wx.rgb_color_trait
    import enthought.traits.ui.wx.scrubber_editor
    import enthought.traits.ui.wx.set_editor
    import enthought.traits.ui.wx.shell_editor
    import enthought.traits.ui.wx.table_editor
    import enthought.traits.ui.wx.table_model
    import enthought.traits.ui.wx.tabular_editor
    import enthought.traits.ui.wx.text_editor
    import enthought.traits.ui.wx.themed_button_editor
    import enthought.traits.ui.wx.themed_cell_renderer
    import enthought.traits.ui.wx.themed_checkbox_editor
    import enthought.traits.ui.wx.themed_control
    import enthought.traits.ui.wx.themed_slider_editor
    import enthought.traits.ui.wx.themed_text_editor
    import enthought.traits.ui.wx.themed_vertical_notebook
    import enthought.traits.ui.wx.themed_vertical_notebook_editor
    import enthought.traits.ui.wx.themed_window
    import enthought.traits.ui.wx.title_editor
    import enthought.traits.ui.wx.toolkit
    import enthought.traits.ui.wx.tree_editor
    import enthought.traits.ui.wx.tuple_editor
    import enthought.traits.ui.wx.ui_base
    import enthought.traits.ui.wx.ui_editor
    import enthought.traits.ui.wx.ui_live
    import enthought.traits.ui.wx.ui_modal
    import enthought.traits.ui.wx.ui_panel
    import enthought.traits.ui.wx.ui_wizard
    import enthought.traits.ui.wx.value_editor
    import enthought.traits.ui.wx.view_application
    import enthought.traits.ui.wx.extra
    import enthought.traits.ui.wx.extra.led_editor
    import enthought.traits.ui.wx.extra.windows
    import enthought.traits.ui.wx.extra.windows.flash_editor
    import enthought.traits.ui.wx.extra.windows.ie_html_editor