LPPsystem pulsePropagation

	SPsystems
		SPsystem senderCell from senderCell.sps
		SPsystem pulsingCell from pulsingCellRelay.sps
		SPsystem boundaryCell from boundaryCell.sps
	endSPsystems

	lattice rectangular from lattice.lat

	spatialDistribution
		
		positions for boundaryCell
			parameters
				parameter i = 0:1:51
				parameter j = 0:11:11
			endParameters
			coordinates
				x = i
				y = j
			endCoordinates
		endPositions
			
		positions for boundaryCell
			parameters
				parameter i = 0:51:51
				parameter j = 0:1:10
			endParameters
			coordinates
				x = i
				y = j
			endCoordinates
		endPositions

		positions for senderCell
			parameters
				parameter i = 1:1:5
				parameter j = 1:1:10
			endParameters

			coordinates
				x=i
				y=j
			endCoordinates
		endPositions

		positions for pulsingCell
			parameters
				parameter i=6:1:50
				parameter j=1:1:10
			endParameters
		
			coordinates
				x=i
				y=j
			endCoordinates
		endPositions

	endSpatialDistribution

endLPPsystem
