#!/usr/bin/env python

from __future__ import with_statement
import sys
import time

#print sys.argv

if len(sys.argv) < 2:
    print 'error: no file specified'
    exit(1)

# assume sys.argv = [expect_tester stdout_file sleep_seconds]

with open(sys.argv[1]) as f:
    stdout = f.readlines()

if len(sys.argv) > 2:
    sleep_seconds = float(sys.argv[2])
else:
    sleep_seconds = 0.2

for line in stdout:
    sys.stdout.write(line)
    time.sleep(sleep_seconds) 

exit(0)